"""Remove active field, use date-based activation

Revision ID: 3dbfcbf86bcf
Revises: f7bc9614e052
Create Date: 2025-12-05 11:53:22.870631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbfcbf86bcf'
down_revision = 'f7bc9614e052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
