"""Add rank to Player

Revision ID: 91ce4dfd63b4
Revises: cc704dd8a10b
Create Date: 2025-12-05 11:19:06.504174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ce4dfd63b4'
down_revision = 'cc704dd8a10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
