"""Add active field to Team model

Revision ID: f7bc9614e052
Revises: 91ce4dfd63b4
Create Date: 2025-12-05 11:49:11.956691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bc9614e052'
down_revision = '91ce4dfd63b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
    
    # Set all existing teams to active=True
    op.execute("UPDATE team SET active = 1 WHERE active IS NULL")
    
    # Now make it NOT NULL
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('active', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
